### ISSUE TITLE
failed to download when run cmake ../

### ISSUE THREAD

**Issue by feijiang1** [intel/compute-samples#1]
In ubuntu 16.04, when run cmake ../, I encountered following downloading problem:

-- Downloading...
   dst='/home/share/worksapce/opencl_compiling/new/compute-samples/third_party/downloads/opencl-external/opencl-headers-prefix/src/de26592167b9fdea503885e40e8755393c56523d.zip'
   timeout='none'
-- Using src='https://github.com/KhronosGroup/OpenCL-Headers/archive/de26592167b9fdea503885e40e8755393c56523d.zip'
-- Retrying...

I can use curl or wget command to download the zip package successfully. It seems the proxy problem, but I tried to add proxy setting in CMakeLists.txt, still failed:
set(ENV{http_proxy}  "http://proxy.cd.intel.com:911")
set(ENV{https_proxy}  "https://proxy.cd.intel.com:911")

Additionally I tried to download de26592167b9fdea503885e40e8755393c56523d.zip manually, and placed in under compute-samples/third_party/downloads/opencl-external/opencl-headers-prefix/src, but still failed with following log:

-- File already exists but no hash specified (use URL_HASH):
  file='/home/share/worksapce/opencl_compiling/new/compute-samples/third_party/downloads/opencl-external/opencl-headers-prefix/src/de26592167b9fdea503885e40e8755393c56523d.zip'
Old file will be removed and new file downloaded from URL.

**Comment by ltowarek** [comment]
Hi,

Yes, it seems to be a proxy problem as Travis on Ubuntu 16.04 works correctly as well as my own Ubuntu 16.04 setup.

Please try running cmake in the following way and let me know if it works:

1. Clean build directory
1. Clean third_party directory
1. `cd build`
1. `http_proxy=your_proxy https_proxy=your_proxy HTTP_PROXY=your_proxy HTTPS_PROXY=your_proxy cmake ..`

Regards,
Lukasz

**Comment by feijiang1** [comment]
Hi, Lukasz

I have tried again, still encountered same problem. Can you help have a double check?

Thanks,
Fei

**Comment by ltowarek** [comment]
Hi,

I double checked again and my workstation with Ubuntu 16.04 works fine. Please try once again the following commands and let me know if the issue is still there:

Set the following proxies in .bashrc
    export http_proxy=http://proxy-chain.intel.com:911
    export https_proxy=http://proxy-chain.intel.com:912
    export ftp_proxy=http://proxy-chain.intel.com:911
    export socks_proxy=http://proxy-chain.intel.com:1080

If you still can't download OpenCL headers then you can use this work-around, but the recommended way of downloading the third-party packages is still via CMake.

1. Clean build directory
1. Clean third_party directory
1. Extract https://github.com/KhronosGroup/OpenCL-Headers/archive/de26592167b9fdea503885e40e8755393c56523d.zip into third_party/opencl/include directory. You should have the following path available - third_party/opencl/include/CL.
1. Call cmake once again

Regards,
Lukasz

**Comment by feijiang1** [comment]
Hi, Lukasz

From your proxy setting, I got some tips, previously I set https proxy as:
https_proxy=https://proxy.cd.intel.com:911
It works when I use wget command, but it failed with cmake downloading.

Then I switch to use:
https_proxy=http://proxy.cd.intel.com:912

cmake works. Thanks a lot for your help.

Another thing need let you know, "https://software.intel.com/file/604709/download" can't be directly downloaded with cmake or wget. Got following error:

-- Downloading...
   dst='/home/share/worksapce/opencl_compiling/new/another/compute-samples/mediadata/downloads/mediadata-external/mediadata-intel-prefix/src/archive.tar'
   timeout='none'
-- Using src='https://software.intel.com/file/604709/download'

Then I download the package from web, then copy it to the folder.

Any way, I have compiled compute samples successfully. :)

**Comment by ltowarek** [comment]
Great news!

Regarding downloading media data. It can be downloaded using cmake and wget. Given that you have default Intel Proxy settings then you need to remove intel.com domain from no_proxy setting. Then CMake will be able to successfully download media data.
