### ISSUE TITLE
DEBUG opencl code

### ISSUE THREAD

**Issue by menggege321** [intel/compute-samples#10]
Hello, how can I debug the kernel code of Intel OpenCL with vs2019 on Windows 10? I've tried the Intel OpenCL SDK on the official website, but I can't debug it. I'm looking forward to your reply, thank you!!!

**Comment by HoppeMateusz** [comment]
Hello,

Here is compute-runtime issue link for reference:
https://github.com/intel/compute-runtime/issues/408#issuecomment-796804935

Mateusz
