### ISSUE TITLE
The solution don't build successfully.

### ISSUE THREAD

**Issue by Cyitao** [intel/compute-samples#5]
First , When I download the dependency , I find that the install file is wrong , the boost download address is wrong. 

When I install all the dependency, i use cmake to generate the solutions . the error occurs as follow:

_CMake Warning (dev) at cmake/import_libpng.cmake:33 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable PNG_ROOT is set to:

    C:/Users/YitaoChang/Desktop/compute-samples-master/scripts/install/third_party/libpng

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:35 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPNG.cmake:52 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable ZLIB_ROOT is set to:

    C:/Users/YitaoChang/Desktop/compute-samples-master/scripts/install/third_party/zlib

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  cmake/import_libpng.cmake:33 (find_package)
  CMakeLists.txt:35 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/import_mediadata.cmake:23 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/scripts/install/mediadata/yuv".
Call Stack (most recent call first):
  CMakeLists.txt:36 (include)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/goal_1280x720.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_search/CMakeLists.txt:52 (install_resources)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/goal_1280x720.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_hme/CMakeLists.txt:56 (install_resources)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/goal_1280x720.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_hme/CMakeLists.txt:71 (install_resources)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/goal_1280x720.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_intra/CMakeLists.txt:53 (install_resources)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/goal_1280x720.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_wpp/CMakeLists.txt:56 (install_resources)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/football_interlaced_720x480.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_interlaced/CMakeLists.txt:44 (install_resources)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/football_interlaced_720x480.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_interlaced/CMakeLists.txt:53 (install_resources)

CMake Error at cmake/custom_functions.cmake:105 (file):
  file COPY cannot find
  "C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/goal_1280x720.yuv".
Call Stack (most recent call first):
  compute_samples/applications/vme_interop/CMakeLists.txt:56 (install_resources)_

**Comment by ltowarek** [comment]
Hi,

It seems that you have not properly installed mediadata:
`CMake Error at cmake/custom_functions.cmake:105 (file):
file COPY cannot find
"C:/Users/YitaoChang/Desktop/compute-samples-master/mediadata/merged/yuv/goal_1280x720.yuv".`

Regarding Boost address I can successfully download it using existing command line i.e.:
`wget -Uri https://prdownloads.sourceforge.net/boost/boost/1.64.0/boost_1_64_0.zip -OutFile boost_1_64_0.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::InternetExplorer`
It also works when pasted into a web browser - https://prdownloads.sourceforge.net/boost/boost/1.64.0/boost_1_64_0.zip

Please note that AppVeyor uses the same scripts and the build passes:
- Build instruction: https://github.com/intel/compute-samples/blob/master/appveyor.yml
- Build results: https://ci.appveyor.com/project/intel/compute-samples

I have also manually verified that the build instruction described in [BUILD.md](https://github.com/intel/compute-samples/blob/master/BUILD.md) works as expected:
```
git clone https://github.com/intel/compute-samples.git
cd compute-samples
powershell scripts\install\install_vs2015.ps1
mkdir build
cd build
cmake .. -G "Visual Studio 14 2015 Win64"
cmake --build . -- /m
```

Please let me know if the above commands work also for you. If not then please send me an output of each command.

Regards,
Lukasz

**Comment by Cyitao** [comment]
Dear，
My IDE is VS17, so I run the scripts\install\install_vs2017.ps1 yesterday.When install the boost , the command line report a error: "It can't identify the ./bootstrap ". So I just change the boost download address, and run again. After update the boost download address ,the boost install is right but still fail as I said for the first time.

By the way , the attach you attached seems wrong , the compute-samples folder and scripts folder are in the same directory. Why you first "cd compute-samples"??

Thanks a lot .

**Comment by ltowarek** [comment]
Hi,

After calling `git clone` you need to change the current directory to the directory with the cloned project.

I tried the build instruction with `install_vs2017.ps1`. It properly downloads and installs all dependencies including Boost:
```
git clone https://github.com/intel/compute-samples.git
cd compute-samples
powershell scripts\install\install_vs2017.ps1
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64"
cmake --build . -- /m
```
Could you send me an output of `powershell scripts\install\install_vs2017.ps1` command?

What happens if you open https://prdownloads.sourceforge.net/boost/boost/1.64.0/boost_1_64_0.zip in a web browser? For me it redirects to https://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.zip/download?use_mirror=datapacket and starts downloading Boost after few seconds.

Regards,
Lukasz

**Comment by Cyitao** [comment]
Hi， 
     When I run the install_vs2017.ps1 , report a error as follows:

![捕获](https://user-images.githubusercontent.com/19355822/62351108-3ba4de00-b537-11e9-9c78-7bf3145654f1.JPG)

**Comment by ltowarek** [comment]
Thanks! I think it will be easier if you run `powershell scripts\install\install_vs2017.ps1 > log.txt 2>&1` and post the content of `log.txt` file.
From your screenshot it seems that the downloaded boost file is corrupted (`Unexpected end of archive`).

**Comment by Cyitao** [comment]
Sorry , I run again and the log file are attached.
Please check again, thanks  a lot

[log.txt](https://github.com/intel/compute-samples/files/3460154/log.txt)

**Comment by ltowarek** [comment]
I assume that this log contains modified URL to Boost, because it is still corrupted:
```
+ . "C:\Program Files\7-Zip\7z.exe" x boost_1_64_0.zip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERRORS:
Unexpected end of archive


--
Path = boost_1_64_0.zip
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 2113670
Characteristics = Local

ERROR: Data Error : boost_1_64_0\boost\shared_ptr.hpp


Sub items Errors: 1

Archives with Errors: 1

Open Errors: 1

Sub items Errors: 1
```

Could you run the following commands once again and send me the log:
```
git reset --hard
powershell scripts\install\install_vs2017.ps1 > log.txt 2>&1
```

**Comment by Cyitao** [comment]
Hi
   The log was attached , again.


[log.txt](https://github.com/intel/compute-samples/files/3460246/log.txt)

**Comment by ltowarek** [comment]
Interesting you still have a corrupted archive. What happens if you open https://prdownloads.sourceforge.net/boost/boost/1.64.0/boost_1_64_0.zip in a web browser? Can you successfully download the archive?

**Comment by Cyitao** [comment]
So yesterday I update the download address using follows website:
https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip

**Comment by ltowarek** [comment]
But still your downloaded archive is corrupted - it should has 136 MiB. Now it has 3648 KiB according to 7-Zip. Please make sure that boost_1_64_0 is downloaded successfully from https://prdownloads.sourceforge.net/boost/boost/1.64.0/boost_1_64_0.zip or https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.zip (these archive are the same).

**Comment by Cyitao** [comment]
Hi ,
    Now I update the download address again , and now it can work. 
By the way, I open this solution  in VS17. There are too much projects , and I try to run the median_filter project. And the IDE report error as follows:
![捕获](https://user-images.githubusercontent.com/19355822/62359009-867b2180-b548-11e9-90db-fc99894cfda5.JPG)

**Comment by ltowarek** [comment]
Good news!
There are 56 projects which are easily handled by Visual Studio 2017. Do you run VS in a resource limited environment?
Unfortunately I can't understand the error from your screenshot. Could you provide the same error in English? `clCreateProgramWithIL` is mentioned so maybe you have an OpenCL implementation that does not support OpenCL 2.1? I am not sure without a proper error message.

**Comment by Cyitao** [comment]
Hi，
The error like this :Unable to locate program entry point clCreateProgramWithIL about dynamic link library.
By the way , My intel graphic card is UHD620 and it should support OpenCL 2.1.

**Comment by ltowarek** [comment]
Yes it should support OpenCL 2.1. Could you double check that you have a recent driver version? To do this you can use utility tool like [GPU-Z](https://www.techpowerup.com/download/techpowerup-gpu-z/) in Advanced Tab -> OpenCL -> Platform Version.

**Comment by Cyitao** [comment]
The platform version is opencl 2.1. 

![捕获](https://user-images.githubusercontent.com/19355822/62360484-71ec5880-b54b-11e9-90e3-c4f1949d19ee.JPG)

**Comment by ltowarek** [comment]
It looks like you have an old version of Graphics Driver (24.20.100.6286). Could you install the latest one from [Download Center](https://downloadcenter.intel.com/)?

**Comment by Cyitao** [comment]
Hi,
It seems don't work.

**Comment by ltowarek** [comment]
For me it looks like an issue with an old `OpenCL.dll` in your `PATH` which does not export OpenCL 2.1 entry points. Do you have any OpenCL SDK installed on your system?
What happens if you build official [OpenCL ICD](https://github.com/KhronosGroup/OpenCL-ICD-Loader) manually and put `OpenCL.dll` next to the `median_filter.exe`? For this purpose you can reuse `scripts/install/install_opencl.ps1` , just remove the cleaning part of the script.

**Comment by Cyitao** [comment]
my PC install the opencl sdk 2017.

**Comment by ltowarek** [comment]
I suspect that an old OpenCL ICD Loader (`OpenCL.dll`) prevents successful execution of compute-samples on your system.
To check this the simplest solution is to just build ICD Loader manually and put it next to the `median_filter.exe` so it will be loaded instead of the one from `PATH`.
You can also uninstall OpenCL SDK 2017 and use OpenCL ICD provided with a driver installation.
Other option is to upgrade OpenCL SDK to 2019 version which should contain latest OpenCL headers and OpenCL ICD Loader.
Finally you can also run [OpenCL Conformance Test Suite](https://github.com/KhronosGroup/OpenCL-CTS) and check if OpenCL 2.1 tests are passing e.g. `spirv_new`.

**Comment by Cyitao** [comment]
Hi , 
 Sorry , I'm late.

 As you said , I try to copy origin Opencl.dll and put it to the  folder which contain median_filter.exe.However ,  it still don't work.

And then , I try to check if OPENCL 2.1 tests. Clone the  OpenCL Conformance Test Suite  and build this project using cmake.  During generater the project using cmake , it report error as attached file  shows.Does my PC don't support Opencl 2.1?

[log.txt](https://github.com/intel/compute-samples/files/3470830/log.txt)

Thanks a lot.

**Comment by ltowarek** [comment]
Hi,

As you can see in GPU-Z output, your GPU does support OpenCL 2.1. Unfortunately you have an environment issue that prevents loading OpenCL 2.1 entry points.

Regarding OpenCL CTS, the CMake issue is not related to the OpenCL ICD Loader. You are just using wrong command line. Please follow these steps (they are for Linux, but running them on Windows should be rather straightforward) - https://github.com/KhronosGroup/OpenCL-CTS/blob/master/.travis.yml

Regards,
Lukasz

**Comment by Cyitao** [comment]
Hi , 
Because the driver of Intel's download center can't install successfully  , I use my PC manufacturer DELL download center. After I update graphics driver , the project run successfully.

However , the code builder report a error , "code builder initialization failed -30".The code builder works well use old version driver, when using the latest driver , it will not work. 

I am trying download the opencl sdk 2019, and revert the driver to the old version....

**Comment by ltowarek** [comment]
Closing an old issue. If necessary feel free to reopen it.
