### ISSUE TITLE
Update to Level Zero 1.0 spec

### ISSUE THREAD

**Issue by servesh** [intel/compute-samples#7]
Hi, Are there any plans to update this repo to support Level Zero 1.0 spec.

In addition I think there is a bug in the way ze_info parses UUID.
Refer here: https://github.com/oneapi-src/level-zero-tests/issues/8#issuecomment-674997141
and here: https://github.com/oneapi-src/level-zero-tests/issues/8#issuecomment-675066469

**Comment by ltowarek** [comment]
Hi,

Perfect timing, as we have just uploaded a new version of ze_info with support for Level Zero v1.0.

Thanks for reporting the issue with the UUID representation. I fixed it today.

Regards,
Lukasz
